### ISSUE TITLE
Error in:  vesalius <- rgbPCA(vesalius,slices = 1)  

### ISSUE THREAD

**Issue by marioacera** [WonLab-CS/Vesalius#1]
Hi,

I am trying to run the model on the Human Invasive Ductal Carcinoma breast tissue public data. 
Loading the data with Load_10x_Spatial:

_vesalius <- Load10X_Spatial(
  data.dir,
  filename = "filtered_feature_bc_matrix.h5",
  assay = "Spatial",)_

And after running the prepocessing functions:

_vesalius <- NormalizeData(vesalius)
vesalius <- FindVariableFeatures(vesalius, nfeatures = 2000)
vesalius <- ScaleData(vesalius)_

The function rgbPCA is showing this error:

_> vesalius <- rgbPCA(vesalius,slices = 1)
#-------------------------------------------------------------------------------------------------------------------# 
2021-08-17 12:17:07  Running Principle Component Analysis in 1 slices 
2021-08-17 12:17:08  Converting Loading Values to RGB in slice 1 
2021-08-17 12:21:30  Normalising RGB values 
Error in `[.data.frame`(coordinates, , c("x", "y")) : 
  undefined columns selected_

Any suggestion about how to solve this?
Thanks in advance.

**Comment by patrickCNMartin** [comment]
Hi,

Thank you for testing the Vesalius package. 

This was a mistake on my part and I have now pushed a corrected version. The issue should be fixed.


Please ensure that you remove the old version, and install the new version in a fresh R session. 

Patrick
