### ISSUE TITLE
How to extract predicted labels for barcodes/coordinates?

### ISSUE THREAD

**Issue by akshayMpatel** [WonLab-CS/Vesalius#10]
Hello, 
I have ground truth labels for the barcodes/coordinates in a .csv file and want to compare to predicted labels of those coordinates from Vesalius after I've input the coordinate and gene expression/count matrix and formed rgb and isolated territory images.  I believe the answer lies somewhere in the following example code from the tutorial but I'm not sure where in Vesalius how to actually enter in the labels and then how to read out the predicted labels? 

What is the relationship between homo_cells and my labels per bead/barcode?
```

#------------------------------------------------------------------------------#
# looping over all cells types in homotypic beads
# Keeping everything in a neat little data frame
#------------------------------------------------------------------------------#
by_cell <- [vector](https://rdrr.io/r/base/vector.html)("list",[length](https://rdrr.io/r/base/length.html)(homo_cells))
[names](https://rdrr.io/r/base/names.html)(by_cell) <- [names](https://rdrr.io/r/base/names.html)(homo_cells)
for(i in [seq_along](https://rdrr.io/r/base/seq.html)(homo_cells)){
    [print](https://rdrr.io/r/base/print.html)([length](https://rdrr.io/r/base/length.html)(homo_cells[[i]]))
    if([length](https://rdrr.io/r/base/length.html)(homo_cells[[i]]) <30){
      next()
    } else {
      deg <- [compareCells](https://patrickcnmartin.github.io/Vesalius/reference/compareCells.html)(imageBrain,
                          brainNorm,
                          homo_cells[[i]],
                          method ="wilcox",
                          seed=cortex,
                          logFC = 0.25,
                          pval = 0.01,
                          query=thalamus,
                          minBar = 30)
    }
    if([is.null](https://rdrr.io/r/base/NULL.html)(deg)){next()}
    deg$celltype <- [rep](https://rdrr.io/r/base/rep.html)([names](https://rdrr.io/r/base/names.html)(homo_cells)[i], [nrow](https://rdrr.io/r/base/nrow.html)(deg))
    deg$group_1 <- [rep](https://rdrr.io/r/base/rep.html)("Cortex", [nrow](https://rdrr.io/r/base/nrow.html)(deg))
    deg$group_2 <- [rep](https://rdrr.io/r/base/rep.html)("Thalamus", [nrow](https://rdrr.io/r/base/nrow.html)(deg))
    by_cell[[i]] <- deg
}
by_cell <- [do.call](https://rdrr.io/r/base/do.call.html)("rbind",by_cell)
[write.csv](https://rdrr.io/r/utils/write.table.html)(by_cell, file = "vesalius_terComp_CortexVSThalamus.csv")
```

Many thanks

**Comment by patrickCNMartin** [comment]
I am not sure I understand what you are trying to do here. Based on context, I am guessing there are 2 potential options:

*1. Comparing predicted territories to ground truth territories* 

Once you have your territories (after running `isolateTerritories.array`) you should have a data.frame that contains the barcodes, x coordinates, y coordinates, tile ( this shows the original coordinates before tile expansion), cluster ( that is the color segment) and territory. 

The `territory` column is the predicted territories from Vesalius. You can compare these predicted labels to your ground truth labels. If you are not familiar with cluster comparison, I suggest looking at the [method comparison folder](https://github.com/patrickCNMartin/Vesalius/tree/main/methodComp) in the Vesalius package. 

Here you will find the code used to compare Vesalius to our simulated ground truth labels ([vesaliusSim.R](https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/vesaliusSim.R)). You can also check the [methodComp file](https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/methodComp.R) that contains more code related to comparison. 

*2. Comparing gene expression of cell types between territories*

As shown in the vignette, this section of the code is to compare the expression of cell types between territories. First you need to have assigned cell types annotations for each of each of your barcodes. In our case we use [RCTD](https://github.com/dmcable/spacexr) to decompose each barcode into potential cell types. Here, we selected barcodes that only contained 1 cell type (we coined this as homo typic beads - For more info, please refer to [the Vesalius paper](https://www.embopress.org/doi/full/10.15252/msb.202211080) and [this pre-print](https://www.biorxiv.org/content/10.1101/2022.02.16.480673v1)). 

Once you have those barcodes we can look at the [compareCells](https://patrickcnmartin.github.io/Vesalius/reference/compareCells.html]) function. 

```
compareCells(
  image,
  counts,
  cells,
  seed = NULL,
  query = NULL,
  method = "wilcox",
  logFC = 0.25,
  pval = 0.05,
  minPct = 0.05,
  minBar = 10,
  morphologyFactorSeed = 0,
  morphologyFactorQuery = 0,
  verbose = TRUE
)
```
You will notice that this function requires 3 arguments. The first one is your Vesalius image (the data frame containing your territories), counts (your seurat object containing your counts) and cells. Cells is a simple character vector of the barcodes you want to compare. These barcodes are the barcodes that are associated to your cell type of interest. Say you want to compare neurons between 2 territories, you will subset the barcodes that are labelled as neurons and parse that barcode vector to the cells argument. You select your territories by specifying territory number in `seed` and in `query`.

I have made clarifications in the manual page for this function.

I hope this covers what you were trying to achieve.

**Comment by akshayMpatel** [comment]
Hello, 

Thanks for your help!  

I have ground truth labels for each coordinate, and I have 3,611 coordinates that I input into Vesalius.  So I presume I want to do the first option. 
But the `territory` column from `isolateTerritories.array` has 138,440 rows!

I'm using the processing steps in the first vignette leading up to following code where I extract `territory` as suggested.
```
imageBrain <- isolateTerritories.array(imageBrain,
                                       captureRadius = 0.008,
                                       minBar = 50)

write.csv(imageBrain$territory, "y_pred.csv")
```

"y_pred.csv" has the following with numbers that just increase incrementally to 138,440. 
```
"","x"
"1","isolated"
"2","isolated"
"3","isolated"
"4","isolated"
"5","isolated"
"6","isolated"
"7","isolated"
"8","isolated"
"9","isolated"
"10","isolated"
"11","isolated"
"12","isolated"
"13","isolated"
"14","isolated"
"15","isolated"
"16","isolated"
"17","isolated"
"18","isolated"
"19","isolated"
...
```

My "ground_labels.csv" has the following 3,611 labels for each coordinate.
```
3
1
7
3
5
6
7
3
2
6
7
4
5
3
5
3
6
5
...
```

I need the 3,611 predictions for each coordinate.

Many thanks
