### ISSUE TITLE
Data simulation in Vesalius paper

### ISSUE THREAD

**Issue by pacificma** [WonLab-CS/Vesalius#11]
Dear Authors, I wonder if you could share the simulated data sets that were used in the paper or the code for generating them? Thank you!

**Comment by patrickCNMartin** [comment]
Hi,

you can find the code used to generate the simulated data sets [here](https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/simulate.R).

We provide all code related to simulations and method comparison in the [methodComp folder](https://github.com/patrickCNMartin/Vesalius/tree/main/methodComp).

Hope this helps!

**Comment by pacificma** [comment]
> Hi,
> 
> you can find the code used to generate the simulated data sets [here](https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/simulate.R).
> 
> We provide all code related to simulations and method comparison in the [methodComp folder](https://github.com/patrickCNMartin/Vesalius/tree/main/methodComp).
> 
> Hope this helps!

Thank you for the help! There are some data files needed as input to simulate data. I wonder if I could find those files somewhere as well.

**Comment by patrickCNMartin** [comment]
Yes - I was just about to edit my comment to let you know about that. 

As described in the methods section, we used a sampling strategy by randomly taking barcodes from Slide-seq data. 

You can find Slide-seq data [here](https://singlecell.broadinstitute.org/single_cell/study/SCP815/highly-sensitive-spatial-transcriptomics-at-near-cellular-resolution-with-slide-seqv2#study-summary). We specifically used Puck_200115_08.

We annotated this data set by using [RCTD](https://github.com/dmcable/spacexr) and a reference taken from [this paper](https://doi.org/10.1016/j.cell.2018.07.028).

As described in the paper, we deconvolute Slide-seq beads using RCTD and then we selected only the beads that had a single cell type associated to them (homotypic beads) .

For the simulations, you will need to run RCTD on Slide-seq Puck_200115_08 and the reference data. We saved this as Seurat object. This is what we are loading. The count matrix is simply the count matrix from Slide-seq Puck_200115_08.

While this is what we used in our simulations, as long as you have a count matrix and cell types associated to each barcode, you will be able to create simulated data sets. Please be advised that some samples will not always work. 



[Simulation_pure_3_3_5.csv](https://github.com/patrickCNMartin/Vesalius/files/9736002/Simulation_pure_3_3_5.csv)


Just in case, I have attached one of our simulated data sets. You will still need the count matrix. 

PS: I have recently changed position and I am still in the process of recovering my data from my previous job. If required, I am happy to share the rest of our simulated data sets once I have them. There are 80 of them in total.
