### ISSUE TITLE
Continuation of previous issue #10

### ISSUE THREAD

**Issue by akshayMpatel** [WonLab-CS/Vesalius#12]
Hello, 

Thanks for your help!  

I have ground truth labels for each coordinate, and I have 3,611 coordinates that I input into Vesalius.  So I presume I want to do the first option. 
But the `territory` column from `isolateTerritories.array` has 138,440 rows!

I'm using the processing steps in the first vignette leading up to following code where I extract `territory` as suggested.
```
imageBrain <- isolateTerritories.array(imageBrain,
                                       captureRadius = 0.008,
                                       minBar = 50)

write.csv(imageBrain$territory, "y_pred.csv")
```

"y_pred.csv" has the following with numbers that just increase incrementally to 138,440. 
```
"","x"
"1","isolated"
"2","isolated"
"3","isolated"
"4","isolated"
"5","isolated"
"6","isolated"
"7","isolated"
"8","isolated"
"9","isolated"
"10","isolated"
"11","isolated"
"12","isolated"
"13","isolated"
"14","isolated"
"15","isolated"
"16","isolated"
"17","isolated"
"18","isolated"
"19","isolated"
...
```

My "ground_labels.csv" has the following 3,611 labels for each coordinate.
```
3
1
7
3
5
6
7
3
2
6
7
4
5
3
5
3
6
5
...
```

I need the 3,611 predictions for each coordinate.

Many thanks

_Originally posted by @akshayMpatel in https://github.com/patrickCNMartin/Vesalius/issues/10#issuecomment-1292950152_

**Comment by patrickCNMartin** [comment]
As described previously, please be sure that the parameters used to isolate your territories are not so stringent as to return only "isolated" patches. If you are suing Visium data, I would not recommend setting `minBar` to 50. 

Furthermore, as described previously, you can look at the [method comparison files](https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/vesaliusSim.R]) to gain a better understanding of how to use vesalius for method benchmarking. 

EDIT: The link adds character that creates a dead link. Here it is as plain text:
https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/vesaliusSim.R


In summary, the `isolateTerritories.array` function provides the isolated territory labels. This comes in the form of an "image data frame" which includes the coordinates and labels for all pixels. The original pixel location is described in the `tile` column with 1 being the centre pixels and 0 being all other pixels related to the tile. To select the centre pixel i.e the pixel containing the original barcode location, you can use the following:

```
 ves <- isolateTerritories.array(ves, captureRadius=0.1,minBar=0) %>%
          filter(tile==1) %>%
          distinct(barcodes, .keep_all =TRUE)
```

Once you have that, you will need to make sure that your barcodes align with your ground truth labels. You could for example use the following approach:

```
library(mclust)
library(mcclust)
aligned <- match(ves$barcodes, barcodes_of_your_ground_truth_labels)
you_ground_truth_labels <- you_ground_truth_levels[aligned]
ari <- adjustedRandIndex(ves$territory, you_ground_truth_labels)
vi <- vi.dist(ves$territory,y ou_ground_truth_labels)
```

You will probably have to modify this code for your own needs. The idea is to re-align the territories with your ground truth labels. Here I show how you could do that using Adjusted Rand Index and Variation of information metrics.

**Comment by akshayMpatel** [comment]
Thank you for your help, I really appreciate it! 
1) But with the settings above, I got 3,598 predicted labels, not 3,611 - the number of input coordinates and ground truth labels I have. What I need is a territory prediction for each original coordinate in the Visium data. How can I access those predictions? 
2) Will the Visium data work when I use the following from one of your workarounds to read in the data? Where locs contains barcodes as indices 1,2... and x,y are the coordinates.
```
bead <- new(Class = 'SlideSeq', assay = 'Spatial', coordinates = locs[,c("x","y")])
rownames(bead@coordinates) <- locs$barcode
```

After I get this I can worry about ari or vi scores, right?




To avoid potential confusion, the following is the code I'm using. Maybe I'm doing something wrong reading in the data. I'm attaching the coord and label files (counts file too large). The counts file is also a csv with just counts, which needs to be transposed so that barcodes are columns and genes are rows. The order is maintained with the coord and label files to enable use of indices (ie 1,2,3 ...) instead of barcodes. 

[maynard_noNA_151673_coords.csv](https://github.com/patrickCNMartin/Vesalius/files/9888480/maynard_noNA_151673_coords.csv)
[maynard_noNA_151673_labels.csv](https://github.com/patrickCNMartin/Vesalius/files/9888481/maynard_noNA_151673_labels.csv)
 :
```

slideTag <- c("151673")

nfeatures <- 100
countList <- list()
for(i in 1){#seq_along(slideTag)){
  message(paste0("Loading Bead file: maynard_noNA_",slideTag[i]))

  slideBeads = paste0("/data/scRNAseq_data/maynard/maynard_noNA_",slideTag[i],"_coords.csv")
  locs <- read.table(slideBeads, header = FALSE, sep = ',') # row names integers, coords
  colnames(locs) <- c('x', 'y')
  locs <- cbind(barcode = c(1:nrow(locs)), locs)
  message(paste('Number of coords', nrow(locs)))
  bead <- new(Class = 'SlideSeq', assay = 'Spatial', coordinates = locs[,c("x","y")])
  rownames(bead@coordinates) <- locs$barcode
  
  message(paste0("Loading Count file: maynard_noNA_",slideTag[i]))
  
  slideCounts = paste0("/data/scRNAseq_data/maynard/maynard_noNA_",slideTag[i],"_UMImatrix.csv")
  cnt <- read.table(slideCounts, header = FALSE, sep = ',') #maynard UMIMatrix has no header or rows, row.names=NULL forces integer row names
  cnt <- t(as.matrix(cnt)) # transpose to genes x barcodes
  colnames(cnt) <- c(1:ncol(cnt)) # give barcode column names
  #cnt <- cbind(Gene = c(1:nrow(cnt)), cnt) # add column for gene row names
  rownames(cnt) <- c(1:nrow(cnt))
  
  count <- CreateSeuratObject(cnt, assay ="Spatial")
  bead <- bead[Cells(x = count)]
  DefaultAssay(object = bead) <- "Spatial"
  count[["slice1"]] <- bead
  
  count <- NormalizeData(count)
  count <- FindVariableFeatures(count, nfeatures = nfeatures)
  count <- ScaleData(count)
  message(paste0("Seurat Pre-Processed Data: maynard_noNA_",slideTag[i]))
   
  count <- rgbUMAP(count, pcs =30, conserveSparse = FALSE)
  countList[[i]] <- count
  
  filenames <- paste0(IP,"UMAP_to_RGB_log_",nfeatures,"_","maynard_noNA_",slideTag[i],".csv")
  exportRGB.csv(count,file = filenames)

}
imageBrain <- buildImageArray(countList[[1]],
                              filterGrid = 0.01,
                              filterThreshold = 0.9975,
                              resolution = 40,
                              cores = 10)

imageBrain <- iterativeSegmentation.array(imageBrain, colDepth =11,
                                          smoothIter = 20,
                                          method = c("iso","box"),
                                          sigma=1,box = 15,
                                          useCenter = T)

#imageBrain <- isolateTerritories.array(imageBrain,
#                                       captureRadius = 0.1,
#                                       minBar = 0)

ves <- isolateTerritories.array(imageBrain, captureRadius=0.1,minBar=0) %>%
  filter(tile==1) %>%
  distinct(barcodes, .keep_all =TRUE)
...

```

**Comment by patrickCNMartin** [comment]
To answer your questions:

1. There is a certain amount of filtering that occurs to remove stray bead or low information beads. This happens both with Vesalius and Seurat. When you create your image array, set `filter_threshold` to 1 and set `tensor_resolution` to 100 as well.
2. As described previously, the code you are using is for slide-seq or it is a workaround for other data types that are not supported by Seurat at the time of writing.  Vesalius has a Visium section in the vignette that is more appropriate. Furthermore, I also have suggested to look at [this file](https://github.com/patrickCNMartin/Vesalius/blob/main/methodComp/vesalius.R). The commented out section at the bottom does bulk comparison on the manyard data set (12 DLPFC data sets). You will have to add the filtering of tiles and scoring yourself but I have provided that code above. 

As for the data that you provide in your comment, I believe that this goes beyond any concerns or issue with vesalius. I am not sure why you do not have the barcodes attached to your labels nor coordinates but I would strongly advise you to make sure they are present. For any tool that you will use, you have to guarantee that your labels will be in the right order. The barcodes are crucial in insuring that you can align your data properly.

**Comment by akshayMpatel** [comment]
1) thanks for clarifying that. Now I should get back number predictions = number of ground truth labels = number of coords
2) very useful thank you for pointing me to that. 

In my code I replace the barcodes with unique integer sequence 1,2,3.... Just curious why that doesn't suffice as barcodes?

**Comment by patrickCNMartin** [comment]
You can use whatever names you like as long as you can ensure that they are being aligned. The barcode names in vesalius need to align with barcode names in your data.

**Comment by akshayMpatel** [comment]
Can I trust that the barcodes from the code provided for `ves` and subsequently `ves$territory` keeps barcode correspondence? As in, does `ves$territory` output line for "12" corresponds to my barcode "12" and hasn't been filled in like it must have been in the 100k barcodes?

**Comment by patrickCNMartin** [comment]
No - there is a reordering of barcodes due to the transition from data frame to images and images back to data frame. That is why you need to have corresponding barcodes to reorder the output of vesalius. As I said, I strongly advise you to have barcode names along side your labels if you want to make comparisons and not just a single column of integers with no context. At least you should have a data frame with `barcodes` and `your_ground_truth_lable`.  With that you can ensure that both barcodes line up for comparison. 


As I have said previously, the output of that function returns values for all pixels not just the original barcode position. That is why you need to use `filter(tile == 1)`. There are many more pixels than spots when you generate images using vesalius. Each spot is expanded into a tile to fill in the gaps between spots and vesalius returns all pixel. 

For your purposes, you can ignore all other pixels other than the centre (the one where `tile ==1`). Then, you will need to reorder your labels to make sure they align between vesalius territories and ground truth labels.

**Comment by akshayMpatel** [comment]
I see. So if I use `filter(tile == 1)`, set filter_threshold to 1, and set tensor_resolution to 100 as you recommend, only then will I get 1:1 alignment, for example, between my barcode "12" for that spot, and territory "12" in vesalius output? That is they point to the same spot coordinate? 

Just to be clear, the "1", "2", in my vesalius output above are the barcodes I input into vesalius? or do I access the barcodes in another column of `ves`?
Just curious, how would the barcodes have been 'expanded' to multiple pixels for each spot, if I used actual barcodes?

**Comment by patrickCNMartin** [comment]
No. They are not in the same order. You need to reorder your ground truth labels to match those in vesalius or vice versa.

**Comment by akshayMpatel** [comment]
Yes now it makes sense!! The "1", "2", above are not barcodes. The `barcodes `column in `ves` contains the barcodes from the set of barcodes I entered.

**Comment by patrickCNMartin** [comment]
Yes - there is a column in the output called barcodes. Whatever name you use will be there. You need to make sure that those names line up with the names you have associated to your ground_truth labels. 

For more information about the tilling , please refer to the paper.

**Comment by akshayMpatel** [comment]
Thank you so much for your help! I very much appreciate it.

Unfortunately I'm still only getting 3,608 territories instead 3,611, after updating parameters as suggested while creating the image array.

**Comment by akshayMpatel** [comment]
Thank you, you've been so helpful to me to understand and use Vesalius. I'm sorry for my confusion earlier and especially for seeming to have to repeat the same question to get to the bottom of my confusion - which came from a simple misunderstanding of barcode representation in output data frame!

But I'm still getting 3,608 territories instead of 3,611 with the settings recommended - filterThreshold=1, resolution=100 during image array creation. I tried just filtering for tile==1 but got ~11k territories. Are there any other things I could try?

**Comment by akshayMpatel** [comment]
Thank you, you've been so helpful to me to understand and use Vesalius. I'm sorry for my confusion earlier and especially for seeming to have to repeat the same question to get to the bottom of that confusion - which came from overlooking barcode representation in output data frame.

I updated my parameters with those from the code you provided for the 12 slices of DLPFC Visium data, thank you. However, I consistently get 1 less territory from vesalius than my labels for all 12 slices, eg 3,610 vs. 3,611. Any clues as to why this occurs? 

I updated my code to use 
- buildImageArray(...filterGrid=1, resolution = 100, filterThreshold = 1)
- equalizeHistogram(... sleft = 15,sright =15)
- iterativeSegmentation.array(...,colDepth = seq(15,n[count], by =-2), smoothIter = 1, method = c("median","iso"),sigma=1,box = 13, useCenter = T) # including n <-c(7,7,7,7,5,5,5,5,7,7,7,7)
- isolateTerritories.array(...captureRadius = 0.035,minBar =5) %>% filter(tile==1) %>% distinct(barcodes, .keep_all =TRUE)

**Comment by patrickCNMartin** [comment]
I believe that might be a bug as I have no idea where that might be coming from. I am currently working on a new version of the package that runs very differently. I will check to see if this occurs there as well.

In the mean time, I don't think that a drop in a single barcode will affect your analysis in anyway.

**Comment by patrickCNMartin** [comment]
I hope this won't be too much of an issue. 

I will leave this thread open until the issue is resolved or I push the development version to main. I will make sure that this doesn't occur.

Thank you for pointing it out by testing vesalius. I really appreciate it.

**Comment by patrickCNMartin** [comment]
Hi,

I have made a fix that I hope will fix the issue. Please let me know if you are still getting one less barcode.

The issue was related to a using `>=` instead of `>` during the filtering. Minor bug but one that needed to be fixed.

**Comment by patrickCNMartin** [comment]
Hi,

I have made a fix to this issue. It was related to the way the filtering threshold were being set. (`>=` instead of using `>`)

You can re-install the package from github (main branch)

Let me know if you have any issues.

**Comment by akshayMpatel** [comment]
Yes I am now getting equal number of predictions to spots, no longer one less. Thank you.
