### ISSUE TITLE
'arguments imply differing number of rows' Error during Converting Sparse Matrix to Matrix

### ISSUE THREAD

**Issue by akshayMpatel** [WonLab-CS/Vesalius#8]
Using my own data I get:
```
2022-09-12 08:28:38  Converting Sparse Matrix to Matrix 
Error in data.frame(rownames(coordinates), coordinates[, c("x", "y")],  : 
  arguments imply differing number of rows: 0, 33538

```
My UMImatrix has 33538 columns and 3566 rows. Given it doesn't have any rownames or header, just counts.

The error seems to eminate from 

 `count <- rgbUMAP(count, pcs =30, conserveSparse = FALSE)
`
Trying to reproduce the issue with the vignette with Slide-seqV2 data:
```
Loading Bead file Puck_200115_08
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names

```

My coordinate .csv file has the same format for Slide-seqV2 coordinates file, including 'barcodes,xcoord,ycoord' header. However for my coordinates file the barcodes column consist of '1' to '3566' instead of the barcode letter sequences.

**Comment by patrickCNMartin** [comment]
Hi,

could you show me the exact code you are using prior to running rgbUMAP?

It should be noted that `rgbUMAP` takes a Seurat object as input. As such, make sure that your Seurat object contains all the information for a valid Spatial Seurat Object. Furthermore, I would strongly advise you to name the columns and rows of your count matrix. Both Seurat and Vesalius rely on these names to match coordinate barcodes to count barcodes as well as providing gene information. As a reminder, it is customary to use barcodes as columns and genes as rows. The barcode names of your count matrix should match the barcode names you have in your coordinate file. 

If you are unfamiliar with manipulating Seurat objects, you can use the following template code to create Seurat objects with your own data. Seurat does not provide templates for all Spatial transcriptomic assays.

```
# First Load your data into R 
counts = "your count data - loaded as a matrix or sparse matrix with rows as genes and columns as barcodes"
locs  = "your coordinates with barcode, x,  and y" 
  
# Second ensure that you have matching barcodes between both files
# Then you can create a SlideSeq object using your own data 
ss <- new(Class = 'SlideSeq', assay = "Spatial", coordinates = locs[,c("x","y")])
rownames(ss@coordinates) <- locs$barcode

st <- CreateSeuratObject(counts, assay ="Spatial")
ss <- ss[Cells(x = st)]
DefaultAssay(object = ss) <- "Spatial"
st[["slice1"]] <- ss

```
The `st` object will be a Seurat object containing your coordinates and counts. You can parse this object to `rgbUMAP`.

**Comment by akshayMpatel** [comment]
Thank you @patrickCNMartin for your timely response. This was helpful. I believe I was able to load my data:
I added rows and columns to the counts and location matrices. I also needed to take the transpose of my counts matrix.

1. I notice 'barcode' and 'gene' colnames are lost in setting up the seurat objects, while only their respective col values are used as rownames. Are these identifiers ('barcode', 'gene') no longer important in further processing? They are implicitly understood as the rownames?
2. To add multiple slides, would I then use `st[["slice2"]] <- ss` etc?

**Comment by patrickCNMartin** [comment]
1. All names should be handled by Seurat internally. I believe that when using the `str` function you will not always see the row names if they are present. It should also be noted that it depends on what part of the Seurat object you are looking at. 

If you are looking at the `meta.data` ( obtained by `FetchData`) you don't have gene information. You can all try `GetAssayData(counts, slot = "data")` for processed data and `GetAssayData(counts, slot = "counts")` for raw counts.  

If you want to get your coordinates, you can use `GetTissueCoordinates`.

2. Unfortunately, I am not sure if Seurat handles multiple slices in that way. From my understanding, I don't think that you can add multiple slice in that way. 

Please be advised that this code is taken from the Seurat source code to bypass restrictions on spatial transcriptomic data types. At the the time of writing, Seurat only handled Visium data and Slide-seq data.

**Comment by akshayMpatel** [comment]
Yes thank you very much for showing how to manually put spatial data into Seurat with its source code in a general way. My project may require that I do the same on a larger scale actually, so this is useful.
